{
 "title": "aws_cost_usage",
 "time": { "from": "2025-10-17T09:34:17.124Z", "to": "2025-10-17T21:34:17.124Z" },
 "panels": [
  {
   "title": "Total AWS Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "finopsdb",
     "rawSql": "SELECT SUM(amount) FROM finopsdb.aws_cost_usage GROUP BY service LIMIT 50 "
    }
   ]
  },
  {
   "title": "Cost by Service",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "finopsdb",
     "rawSql": "SELECT \r\n  service,\r\n  SUM(amount) AS total_cost\r\nFROM aws_cost_usage\r\nWHERE start_date >= DATE_SUB(CURDATE(), INTERVAL 1 DAY)\r\nGROUP BY service\r\nORDER BY total_cost DESC;\r\n"
    }
   ]
  },
  {
   "title": "Daily Cost Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyINR" } },
   "targets": [
    {
     "dataset": "finopsdb",
     "rawSql": "SELECT \r\n  start_date AS time,\r\n  SUM(amount) AS daily_cost\r\nFROM aws_cost_usage\r\nGROUP BY start_date\r\nORDER BY start_date ASC;"
    },
    {
     "dataset": "finopsdb",
     "rawSql": "SELECT \r\n  service,\r\n  SUM(amount) AS total_cost\r\nFROM aws_cost_usage\r\nWHERE start_date >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)\r\nGROUP BY service\r\nORDER BY total_cost DESC;"
    }
   ]
  }
 ]
}